- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    status: installed

- name: remove old contents
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: create a applicatin directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory


- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes