- name: prometheus server
  ansible.builtin.import_tasks:
    file: server.yml
  when: prometheus_server


- name: node_exporter
  ansible.builtin.import_tasks:
    file: exporter.yml
  when: node_exporter


